### PR TITLE
Draft: Merge RosBE Unix and Windows into a single project and general decoupling

### PR DESCRIPTION
**Pull request by lakor64**
The following PR is an attempt at unifying the build system of ReactOS for Unix and Windows into a single script and project.
I've also decided to apply some refactoring in the scripting code to decouple actual package build steps with the main script.

**NO UPGRADE INTENDED:** All the modules still reflect the exact same version as RosBE (eg. gcc or binutils)

My new architecture is an attempt to solve the following issues or hints that happend to me while trying to upgrade Rosbe gcc:
- There were currently 3 scripts to maintain for anything related to compiler or tools (Windows mingw32, Windows mingw64 and Unix). Those scripts were pretty much the same with the few expection of one or two extra arguments
- Unix doesn't have an triplet or architecture concept, you cannot specify to build an amd64 gcc under Unix
(For more info I would suggest looking at my messages under mattermost #rosbe )

This is the following changes I have applied to the build system:
- Converted all possible Windows tools to support Unix (or provide bash scripts for alternatives), this might be usefull for getting things like playsound back
- Completely separate build commands for each module from the main builder, this has the advantage of easily adding new modules (like clang) without altering the original code, the workflow was inspired from PKGBUILD
- Added support for automatic download of modules from the internet with checking for sha256, this allows to avoid using svn.reactos.org prepatched version and apply patches on the fly which can also, in my opinion, be a better option to understand what changes ReactOS added
- Cleaned up old patching files (eg. for gcc4)
- Added a bunch of new command line to exclude building tools, modules or specific architectures
- The script can now build multiple versions of GCC at the same time, more testing for the prefix is needed but it's a starting point
- Separated the various modules of GCC buildstep as they shouldn't be triplet specific
- Added an option to run build commands with msys2 inside the package files, in case a specific package needs to be built this way it will be runned from a forwarder
- Added an ability to resume builds after a fail, this was done to potentially patch and continue building

What's not working:
- [ ] Fix docker container
- [ ] Fix nsis installer
- [x] Fix flex build and installation under Windows (I am working on patching flex to add support for mingw64 to avoid using msys2)
- [ ] Fix and test gcc builds (amd64 tests pending)
- [x] Fix possible issues when building ninja (seems a rather trivial bug that might require an off-tree patch)
- [ ] Test an actual compilation with ReactOS and verify no new regression was added
- [ ] Figure out a way to fix 
- [ ] Unify the readme pdf and similar things into one single thing
- [ ] Final test under WIndows (MSYS2), MacOSX and Linux

### CODE REVIEW

**Comment by Kreijstal** [comment]
I wonder why can't rosbe be packaged for msys2?

**Comment by lakor64** [comment]
> I wonder why can't rosbe be packaged for msys2?

RosBE is intended as a single one-click environment to ReactOS, what would make sense to package on an existing msys2 environment would be a meta-package that contains a Reactos-specific compiler (as it would have different flags from a normal msys2 gcc).
Altrough keep in mind, that the actual developers might have other reasons of why this wasn't considered.

**Comment by Kreijstal** [comment]
> > I wonder why can't rosbe be packaged for msys2?
> 
> RosBE is intended as a single one-click environment to ReactOS, what would make sense to package on an existing msys2 environment would be a meta-package that contains a Reactos-specific compiler (as it would have different flags from a normal msys2 gcc). Altrough keep in mind, that the actual developers might have other reasons of why this wasn't considered.

yeah that would ease the use and accessibility of rosbe as well, since it would be easy to make and pacman would take care of it. It doesn't have to be officially packaged though a PKGBUILD script saves hours. Thank you for your time.

**Comment by lakor64** [comment]
cosidering the idea of going with a PKGBUILD this PR doesn't make sense anymore, I will wait for a better time to eventually open a new pr.

**Pull request closed without merging**
